### ISSUE TITLE
Wrong password in `init.sh` message

### ISSUE THREAD

**Issue by NickCis** [redhatdemocentral/rhcs-generic-loan-demo#1]
Hi,
when `init.sh` finishes it displays a message saying that the [password is `jbossbpm1!`](https://github.com/redhatdemocentral/rhcs-generic-loan-demo/blob/master/init.sh#L214), while the real [password is `bpmsuite1!`](https://github.com/redhatdemocentral/rhcs-generic-loan-demo/blob/master/Dockerfile#L34).

Thanks!

**Comment by eschabell** [comment]
@NickCis thanks, fixed!
